AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - vendor/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Layout/LineLength:
  Max: 140
  Exclude:
    - txray.gemspec

Style/FormatStringToken:
  EnforcedStyle: template

Gemspec/DevelopmentDependencies:
  EnforcedStyle: Gemfile
